"""adds user table

Revision ID: 8bc2eee11f0f
Revises: 
Create Date: 2024-05-09 16:10:03.237913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8bc2eee11f0f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('chat_id', sa.BigInteger(), nullable=True),
                    sa.Column('username', sa.String(), nullable=True),
                    sa.Column('first_name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('chat_id')
                    )
    op.create_table('groups',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('chat_id', sa.BigInteger(), nullable=True),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('username', sa.String(), nullable=True),
                    sa.Column('members', sa.Integer(), nullable=True),
                    sa.Column('language', sa.String(), nullable=True),
                    sa.Column('created_add', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_groups_chat_id'), 'groups', ['chat_id'], unique=True)
    op.create_table('users',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('chat_id', sa.BigInteger(), nullable=True),
                    sa.Column('username', sa.String(), nullable=True),
                    sa.Column('first_name', sa.String(), nullable=True),
                    sa.Column('language', sa.String(), nullable=True),
                    sa.Column('added_by', sa.String(), nullable=True),
                    sa.Column('created_add', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_chat_id'), 'users', ['chat_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_chat_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_groups_chat_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_table('admins')
    # ### end Alembic commands ###
